rem 윈도우에서 작동하는 환경변수 bat파일. cmd창에서 실행하면 됨

set OAUTHLIB_INSECURE_TRANSPORT=1

set SECRET_KEY=g3oCwMxBDWKdRMx4JUucoB369MDsOj6xuUNNUDSKaI1KsKlMdL

set DB_USER=root
set DB_PW=root
set GOOGLE_CLIENT_ID=47258694830-1vikigana4j8c6rkgpuqutb956lhh7om.apps.googleusercontent.com
set GOOGLE_CLIENT_SECRET=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

set OAUTHLIB_INSECURE_TRANSPORT
set SECRET_KEY
set DB_USER
set DB_PW
set GOOGLE_CLIENT_ID
set GOOGLE_CLIENT_SECRET

pause